### PR TITLE
Moved dependencies

### PR DESCRIPTION
**Pull request by athanclark**
Hi there,

Your bower dependencies are all in `devDependencies`; they just needed to be moved so builds can work properly.

### CODE REVIEW

**Comment by jacereda** [comment]
Doh! Thanks!

**Comment by athanclark** [comment]
Would you be willing to publish a new minor version? :)

**Comment by jacereda** [comment]
Done.

**Comment by athanclark** [comment]
Sorry but I don't see a new tag published, or in pursuit: https://pursuit.purescript.org/packages/purescript-pako

**Comment by athanclark** [comment]
@jacereda ping

**Comment by jacereda** [comment]
Forgot the publish, should be ready now.

**Comment by athanclark** [comment]
w00t! Thank you!

**Pull request merged**
